package com.ruoyi.intervention.domain.model;

import com.ruoyi.intervention.domain.enums.ExerciseIntensity;
import com.ruoyi.intervention.domain.enums.ExerciseType;

/**
 * 单日运动处方
 * Daily exercise prescription generated by the rule engine.
 */
public class DailyExercise
{
    private ExerciseType type;
    private ExerciseIntensity intensity;
    private int durationMinutes;   // target duration
    private Integer targetHrMin;   // optional — null if not applicable
    private Integer targetHrMax;
    private int sets;
    private int repsPerSet;
    private String notes;

    public DailyExercise() {}

    public DailyExercise(ExerciseType type, ExerciseIntensity intensity, int durationMinutes)
    {
        this.type = type;
        this.intensity = intensity;
        this.durationMinutes = durationMinutes;
    }

    /**
     * Builder-style setter for heart rate zone.
     */
    public DailyExercise withHeartRateZone(int min, int max)
    {
        this.targetHrMin = min;
        this.targetHrMax = max;
        return this;
    }

    /**
     * Builder-style setter for resistance training parameters.
     */
    public DailyExercise withSets(int sets, int repsPerSet)
    {
        this.sets = sets;
        this.repsPerSet = repsPerSet;
        return this;
    }

    // --- Getters & Setters ---

    public ExerciseType getType() { return type; }
    public void setType(ExerciseType type) { this.type = type; }

    public ExerciseIntensity getIntensity() { return intensity; }
    public void setIntensity(ExerciseIntensity intensity) { this.intensity = intensity; }

    public int getDurationMinutes() { return durationMinutes; }
    public void setDurationMinutes(int durationMinutes) { this.durationMinutes = durationMinutes; }

    public Integer getTargetHrMin() { return targetHrMin; }
    public void setTargetHrMin(Integer targetHrMin) { this.targetHrMin = targetHrMin; }

    public Integer getTargetHrMax() { return targetHrMax; }
    public void setTargetHrMax(Integer targetHrMax) { this.targetHrMax = targetHrMax; }

    public int getSets() { return sets; }
    public void setSets(int sets) { this.sets = sets; }

    public int getRepsPerSet() { return repsPerSet; }
    public void setRepsPerSet(int repsPerSet) { this.repsPerSet = repsPerSet; }

    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }
}
