package com.ruoyi.intervention.domain.model;

import java.time.LocalTime;

/**
 * 睡眠建议
 * Sleep recommendation generated by the rule engine.
 */
public class SleepRecommendation
{
    private LocalTime targetBedtime;
    private LocalTime targetWakeTime;
    private double targetDurationHours;
    private String sleepHygieneAdvice;
    private double currentSleepScore;  // 0-100
    private double targetSleepScore;

    public SleepRecommendation() {}

    public SleepRecommendation(LocalTime targetBedtime, LocalTime targetWakeTime, double targetDurationHours)
    {
        this.targetBedtime = targetBedtime;
        this.targetWakeTime = targetWakeTime;
        this.targetDurationHours = targetDurationHours;
    }

    // --- Getters & Setters ---

    public LocalTime getTargetBedtime() { return targetBedtime; }
    public void setTargetBedtime(LocalTime targetBedtime) { this.targetBedtime = targetBedtime; }

    public LocalTime getTargetWakeTime() { return targetWakeTime; }
    public void setTargetWakeTime(LocalTime targetWakeTime) { this.targetWakeTime = targetWakeTime; }

    public double getTargetDurationHours() { return targetDurationHours; }
    public void setTargetDurationHours(double targetDurationHours) { this.targetDurationHours = targetDurationHours; }

    public String getSleepHygieneAdvice() { return sleepHygieneAdvice; }
    public void setSleepHygieneAdvice(String sleepHygieneAdvice) { this.sleepHygieneAdvice = sleepHygieneAdvice; }

    public double getCurrentSleepScore() { return currentSleepScore; }
    public void setCurrentSleepScore(double currentSleepScore) { this.currentSleepScore = currentSleepScore; }

    public double getTargetSleepScore() { return targetSleepScore; }
    public void setTargetSleepScore(double targetSleepScore) { this.targetSleepScore = targetSleepScore; }
}
