// Auto-generated by scripts/write-local-env.mjs.
// Re-run npm run prepare:local when your Wi-Fi IP changes.
export const localDevConfig = {
  apiBase: 'http://172.16.133.252:8080',
  ieBase: 'http://172.16.133.252:8080',
  wsUrl: 'ws://172.16.133.252:8080/ws',
};
