// Auto-generated by scripts/write-local-env.mjs.
// Re-run npm run prepare:local when your Wi-Fi IP changes.
export const localDevConfig = {
  apiBase: 'http://10.111.247.67:18080',
  ieBase: 'http://10.111.247.67:18080',
  wsUrl: 'ws://10.111.247.67:18080/ws',
};
