// Auto-generated by scripts/write-local-env.mjs.
// Do not edit by hand. Re-run npm run prepare:local when your Wi-Fi IP changes.
export const localDevConfig = {
  apiBase: 'http://192.168.1.102:8080',
  ieBase: 'http://192.168.1.102:8080',
  wsUrl: 'ws://192.168.1.102:8080/ws',
};
